"""
MultiSteg — Multi-Media Steganography Research System (API Backend)

Flask REST API providing:
    - Image steganography (LSB-based, PNG/JPG)
    - Video steganography (frame-based LSB via stegano + FFmpeg)
    - AES-256 encryption with optional zlib compression
    - Research features: capacity estimation, integrity hashing, PSNR metrics

All endpoints return JSON or binary file responses.
Frontend is a separate Next.js application.
"""

import logging
import math
import os
import re
import traceback
import uuid

from flask import Flask, request, send_file, jsonify
from flask_cors import CORS
from werkzeug.exceptions import RequestEntityTooLarge

from steganography import image_steg, video_steg
from encryption.aes_crypto import encrypt, decrypt
from analysis.capacity import estimate_image_capacity, estimate_video_capacity
from analysis.integrity import compute_hash
from analysis.metrics import compute_metrics
from utils.file_handler import save_upload, output_path, get_file_size_str, init_dirs
from utils.payload import pack_payload, unpack_payload


app = Flask(__name__)
app.secret_key = os.environ.get("SECRET_KEY", os.urandom(24).hex())
app.config["MAX_CONTENT_LENGTH"] = 2 * 1024 * 1024 * 1024  # 2 GB upload limit (FFV1 stego videos can exceed 700 MB)

CORS(app)

# Ensure runtime directories exist (also needed when running under Gunicorn)
init_dirs()

# Job progress tracking for long-running operations (video embed)
_job_progress = {}


@app.route("/")
def index():
    return {"service": "MultiSteg backend running"}
# ---------------------------------------------------------------------------
# Health check
# ---------------------------------------------------------------------------

@app.route("/api/health")
def health():
    return jsonify({"status": "ok"})


# ---------------------------------------------------------------------------
# Friendly error mapping
# ---------------------------------------------------------------------------

logger = logging.getLogger(__name__)

_IMAGE_EXTS = {".png", ".jpg", ".jpeg"}
_VIDEO_EXTS = {".mp4", ".mov", ".avi", ".mkv"}

_ERROR_MAP = [
    # (pattern, context_or_None, friendly_message)
    # context=None matches any context; context="embed" only during embedding, etc.
    ("Payload too large", "embed",
     "The selected file does not have enough space to hide the data. "
     "Please use a larger file."),
    ("max_bytes", "embed",
     "The selected file does not have enough space to hide the data. "
     "Please use a larger file."),
    ("not enough space", "embed",
     "The selected file does not have enough space to hide the data. "
     "Please use a larger file."),
    ("Incorrect padding", None,
     "The passphrase is incorrect or the file does not contain hidden data."),
    ("Invalid padding", None,
     "The passphrase is incorrect or the file does not contain hidden data."),
    ("PKCS", None,
     "The passphrase is incorrect or the file does not contain hidden data."),
    ("Decryption failed", None,
     "The passphrase is incorrect or the file does not contain hidden data."),
    ("decompression", None,
     "The passphrase is incorrect or the file does not contain hidden data."),
    ("zlib", None,
     "The passphrase is incorrect or the file does not contain hidden data."),
    ("base64", None,
     "The passphrase is incorrect or the file does not contain hidden data."),
    ("Cannot identify image", None,
     "The file could not be processed. Please upload a valid media file."),
    ("truncated", None,
     "The file appears to be corrupted or incomplete. Please upload a valid file."),
    ("corrupt", None,
     "The file appears to be corrupted or incomplete. Please upload a valid file."),
    ("No video stream", None,
     "The file could not be processed. Please upload a valid video file."),
    ("no frames", None,
     "The file could not be processed. Please upload a valid video file."),
    ("steganography metadata", None,
     "This file does not appear to contain hidden data. "
     "Please upload a stego file generated by this system."),
    ("Permission", None,
     "The server could not save the file. Please try again."),
]


def _friendly_error(exc: Exception, context: str = "processing") -> str:
    """Convert a technical exception into a user-friendly message.

    The full traceback is logged server-side; only a simple sentence is
    returned for the API response.
    """
    raw = str(exc)
    logger.error("[%s] %s: %s", context, type(exc).__name__, raw)
    traceback.print_exc()

    for pattern, ctx_filter, friendly in _ERROR_MAP:
        if pattern.lower() in raw.lower():
            if ctx_filter is None or ctx_filter == context:
                return friendly

    # Fallback generic messages per context
    if context == "embed":
        return ("Something went wrong while hiding the data. "
                "Please try again or use a different file.")
    if context == "extract":
        return ("Something went wrong during extraction. "
                "Please check your file and passphrase and try again.")
    return "An unexpected error occurred. Please try again."


def _validate_file_extension(filename: str, media_type: str) -> str | None:
    """Return an error message if the file extension is unsupported."""
    ext = os.path.splitext(filename)[1].lower()
    if media_type == "image":
        if ext not in _IMAGE_EXTS:
            return ("This file format is not supported. "
                    "Please upload a PNG or JPG image.")
    else:
        if ext not in _VIDEO_EXTS:
            return ("This file format is not supported. "
                    "Please upload a supported video file (MP4, MOV, AVI, or MKV).")
    return None


# ---------------------------------------------------------------------------
# Passphrase strength validation
# ---------------------------------------------------------------------------

def _validate_passphrase(passphrase: str) -> str | None:
    """Return an error message if passphrase is too weak, else None."""
    if len(passphrase) < 8:
        return ("Password too weak. Please use at least 8 characters including "
                "uppercase, lowercase, number, and special character.")
    if not re.search(r"[A-Z]", passphrase):
        return ("Password too weak. Please use at least 8 characters including "
                "uppercase, lowercase, number, and special character.")
    if not re.search(r"[a-z]", passphrase):
        return ("Password too weak. Please use at least 8 characters including "
                "uppercase, lowercase, number, and special character.")
    if not re.search(r"[0-9]", passphrase):
        return ("Password too weak. Please use at least 8 characters including "
                "uppercase, lowercase, number, and special character.")
    if not re.search(r"[!@#$%^&*()_+\-=\[\]{};':""\\|,.<>/?`~]", passphrase):
        return ("Password too weak. Please use at least 8 characters including "
                "uppercase, lowercase, number, and special character.")
    return None


# ---------------------------------------------------------------------------
# Embed
# ---------------------------------------------------------------------------

@app.route("/api/embed", methods=["POST"])
def api_embed():
    """Embed secret data into a cover medium. Returns JSON metadata + download URL."""
    try:
        media_type = request.form.get("media_type", "image")
        passphrase = request.form.get("passphrase", "")
        cover_file = request.files.get("cover_file")
        secret_file = request.files.get("secret_file")
        secret_text = request.form.get("secret_text", "")

        # --- Validation ---
        if not cover_file or not cover_file.filename:
            return jsonify({"error": "Please upload a cover file."}), 400

        if not passphrase:
            return jsonify({"error": "Please enter a passphrase for encryption."}), 400

        pass_err = _validate_passphrase(passphrase)
        if pass_err:
            return jsonify({"error": pass_err}), 400

        if (not secret_file or not secret_file.filename) and not secret_text.strip():
            return jsonify({"error": "Please provide secret text or upload a secret file."}), 400

        # --- Validate file format ---
        fmt_err = _validate_file_extension(cover_file.filename, media_type)
        if fmt_err:
            return jsonify({"error": fmt_err}), 400

        # --- Save cover ---
        cover_path = save_upload(cover_file)

        # --- Prepare secret payload ---
        if secret_file and secret_file.filename:
            file_bytes = secret_file.read()
            secret_name = secret_file.filename
            raw_secret = pack_payload(secret_name, file_bytes)
        else:
            raw_secret = secret_text.strip().encode("utf-8")
            secret_name = "text input"

        # --- Encrypt (compress + AES-256) ---
        encrypted = encrypt(raw_secret, passphrase, compress=True)
        original_size = len(raw_secret)
        encrypted_size = len(encrypted)

        # --- Capacity check + embed ---
        capacity_info = {}
        metrics_info = {}
        output_filename = ""

        if media_type == "image":
            cap = estimate_image_capacity(cover_path)
            capacity_info = cap

            if encrypted_size > cap["max_bytes"]:
                return jsonify({
                    "error": ("The selected image does not have enough space to "
                              "hide the data. Please use a larger image.")
                }), 400

            stego_img = image_steg.embed(cover_path, encrypted, passphrase)
            output_filename = "stego_output.png"
            out_path = output_path(output_filename)
            stego_img.save(out_path, "PNG")

            try:
                metrics_info = compute_metrics(cover_path, out_path)
            except Exception:
                metrics_info = {"note": "Metrics unavailable for this pair."}

        else:
            # Video steganography
            cap = estimate_video_capacity(cover_path)
            capacity_info = cap
            payload_str = encrypted.decode("ascii")  # base64 is ASCII-safe
            output_filename = "stego_output.mkv"
            out_path = output_path(output_filename)

            job_id = request.form.get("job_id", "")

            def _stage_cb(stage, **kwargs):
                if job_id:
                    _job_progress[job_id] = {"stage": stage, **kwargs}

            result = video_steg.embed(
                cover_path, payload_str, passphrase=passphrase,
                output_path=out_path, on_stage=_stage_cb,
            )
            out_path = result["output_path"]
            output_filename = os.path.basename(out_path)
            capacity_info["frame_numbers"] = result["frame_numbers"]
            capacity_info["num_parts"] = result["num_parts"]

        file_hash = compute_hash(out_path)
        file_size = get_file_size_str(out_path)

        return jsonify({
            "success": True,
            "media_type": media_type,
            "download_filename": output_filename,
            "file_hash": file_hash,
            "file_size": file_size,
            "capacity": capacity_info,
            "metrics": metrics_info,
            "secret_name": secret_name,
            "secret_size": original_size,
            "encrypted_size": encrypted_size,
        })

    except RequestEntityTooLarge:
        raise  # let Flask's 413 handler respond
    except Exception as e:
        return jsonify({"error": _friendly_error(e, "embed")}), 500
    finally:
        job_id = request.form.get("job_id", "")
        _job_progress.pop(job_id, None)


@app.route("/api/embed/progress/<job_id>")
def embed_progress(job_id):
    """Poll current processing stage for a video embed job."""
    info = _job_progress.get(job_id, {"stage": "queued"})
    return jsonify(info)


# ---------------------------------------------------------------------------
# Extract
# ---------------------------------------------------------------------------

@app.route("/api/extract", methods=["POST"])
def api_extract():
    """Extract and decrypt hidden data from stego media."""
    try:
        media_type = request.form.get("media_type", "image")
        passphrase = request.form.get("passphrase", "")
        stego_file = request.files.get("stego_file")

        # --- Validation ---
        if not stego_file or not stego_file.filename:
            return jsonify({"error": "Please upload a stego file."}), 400

        if not passphrase:
            return jsonify({"error": "Please enter the passphrase used during embedding."}), 400

        # --- Validate file format ---
        ext = os.path.splitext(stego_file.filename)[1].lower()
        if media_type == "image" and ext not in _IMAGE_EXTS:
            return jsonify({"error": "This file format is not supported. "
                                     "Please upload a PNG or JPG image."}), 400
        if media_type == "video" and ext not in _VIDEO_EXTS:
            return jsonify({"error": "This file format is not supported. "
                                     "Please upload a supported video file (MP4, MOV, AVI, or MKV)."}), 400

        stego_path = save_upload(stego_file)

        # --- Extract ---
        if media_type == "image":
            encrypted = image_steg.extract(stego_path, passphrase)
        else:
            payload_str = video_steg.extract(stego_path, passphrase)
            encrypted = payload_str.encode("ascii")

        # --- Decrypt ---
        decrypted = decrypt(encrypted, passphrase)

        # Unpack payload: recover original filename if present
        original_name, file_data = unpack_payload(decrypted)

        if original_name is not None:
            # File payload — restore with original filename
            download_filename = original_name
            out = output_path(download_filename)
            with open(out, "wb") as f:
                f.write(file_data)
            return jsonify({
                "success": True,
                "is_text": False,
                "media_type": media_type,
                "download_filename": download_filename,
                "decrypted_size": len(file_data),
            })
        else:
            # Plain text payload (no file header)
            try:
                message = file_data.decode("utf-8")
                return jsonify({
                    "success": True,
                    "is_text": True,
                    "media_type": media_type,
                    "message": message,
                    "decrypted_size": len(file_data),
                })
            except (UnicodeDecodeError, ValueError):
                download_filename = "extracted_file.bin"
                out = output_path(download_filename)
                with open(out, "wb") as f:
                    f.write(file_data)
                return jsonify({
                    "success": True,
                    "is_text": False,
                    "media_type": media_type,
                    "download_filename": download_filename,
                    "decrypted_size": len(file_data),
                })

    except RequestEntityTooLarge:
        raise  # let Flask's 413 handler respond
    except ValueError as e:
        logger.error("[extract] ValueError: %s", e)
        return jsonify({"error": "The passphrase is incorrect or the file does not contain hidden data."}), 400
    except Exception as e:
        return jsonify({"error": _friendly_error(e, "extract")}), 500


# ---------------------------------------------------------------------------
# Download
# ---------------------------------------------------------------------------

@app.route("/api/download/<filename>")
def api_download(filename):
    """Download an output file."""
    file_path = output_path(filename)
    if not os.path.exists(file_path):
        return jsonify({"error": "File not found."}), 404
    return send_file(file_path, as_attachment=True)


# ---------------------------------------------------------------------------
# Capacity estimation
# ---------------------------------------------------------------------------

@app.route("/api/capacity", methods=["POST"])
def api_capacity():
    """Estimate capacity for an uploaded cover file."""
    cover_file = request.files.get("cover_file")
    media_type = request.form.get("media_type", "image")

    if not cover_file or not cover_file.filename:
        return jsonify({"error": "No file provided"}), 400

    path = save_upload(cover_file)
    try:
        if media_type == "image":
            info = estimate_image_capacity(path)
        else:
            info = estimate_video_capacity(path)
        return jsonify(info)
    except Exception as e:
        return jsonify({"error": _friendly_error(e, "capacity")}), 500


# ---------------------------------------------------------------------------
# Global error handlers
# ---------------------------------------------------------------------------

@app.errorhandler(413)
def handle_too_large(e):
    return jsonify({"error": "The uploaded file is too large. Maximum size is 2 GB."}), 413

@app.errorhandler(404)
def handle_not_found(e):
    return jsonify({"error": "The requested resource was not found."}), 404

@app.errorhandler(500)
def handle_server_error(e):
    logger.error("Unhandled 500: %s", e)
    return jsonify({"error": "An unexpected error occurred. Please try again."}), 500


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    print("\n  MultiSteg API — Multi-Media Steganography Research System")
    print("  Running at http://127.0.0.1:5000\n")
    app.run(host="0.0.0.0", port=int(os.environ.get("PORT", 5000)), debug=True)
